return {
PlaceObj('ModItemCharacterEffectCompositeDef', {
	'Id', "FarFromHome",
	'object_class', "CharacterEffect",
	'msg_reactions', {},
	'Conditions', {},
	'Modifiers', {},
	'DisplayName', T(961555598847, --[[ModItemCharacterEffectCompositeDef FarFromHome DisplayName]] "Far From Home"),
	'Description', T(752312637169, --[[ModItemCharacterEffectCompositeDef FarFromHome Description]] "Militia soldiers who fight too far from their hometown, especially rookies, face various negative effects such as loss of morale."),
	'type', "Debuff",
	'Icon', "Mod/LXPER6t/Icons/farfromhome.png",
	'Shown', true,
	'ShownSatelliteView', true,
}),
PlaceObj('ModItemCharacterEffectCompositeDef', {
	'Id', "GCMilitia",
	'object_class', "CharacterEffect",
	'msg_reactions', {},
	'DisplayName', T(910546539467, --[[ModItemCharacterEffectCompositeDef GCMilitia DisplayName]] "Grand Chien Militia"),
	'Description', T(621380007867, --[[ModItemCharacterEffectCompositeDef GCMilitia Description]] "A perk every militia solider gets after bootcamp. Which allows them to clean and maintain their weapons."),
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaAndSquads",
	'CodeFileName', "Code/MilitiaAndSquads.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaBiosAndNames",
	'CodeFileName', "Code/MilitiaBiosAndNames.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaCompat",
	'CodeFileName', "Code/MilitiaCompat.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaConflictTracker",
	'CodeFileName', "Code/MilitiaConflictTracker.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaEquipment",
	'CodeFileName', "Code/MilitiaEquipment.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaFinances",
	'CodeFileName', "Code/MilitiaFinances.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaInit",
	'CodeFileName', "Code/MilitiaInit.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaLoyalty",
	'CodeFileName', "Code/MilitiaLoyalty.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaManagement",
	'CodeFileName', "Code/MilitiaManagement.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaMovement",
	'CodeFileName', "Code/MilitiaMovement.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaOverrides",
	'CodeFileName', "Code/MilitiaOverrides.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaPDA",
	'CodeFileName', "Code/MilitiaPDA.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaPerkEffects",
	'CodeFileName', "Code/MilitiaPerkEffects.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaPersonalization",
	'CodeFileName', "Code/MilitiaPersonalization.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaSatelliteConflict",
	'CodeFileName', "Code/MilitiaSatelliteConflict.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaShopController",
	'CodeFileName', "Code/MilitiaShopController.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaStoryParts",
	'CodeFileName', "Code/MilitiaStoryParts.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaTraining",
	'CodeFileName', "Code/MilitiaTraining.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MilitiaUtils",
	'CodeFileName', "Code/MilitiaUtils.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitia",
	'CodeFileName', "Code/PDAMilitia.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaFinances",
	'CodeFileName', "Code/PDAMilitiaFinances.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaHome",
	'CodeFileName', "Code/PDAMilitiaHome.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaHyperlinkHeader",
	'CodeFileName', "Code/PDAMilitiaHyperlinkHeader.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaShop",
	'CodeFileName', "Code/PDAMilitiaShop.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaShopCart",
	'CodeFileName', "Code/PDAMilitiaShopCart.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaShopList",
	'CodeFileName', "Code/PDAMilitiaShopList.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaShopNav",
	'CodeFileName', "Code/PDAMilitiaShopNav.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaShopOrders",
	'CodeFileName', "Code/PDAMilitiaShopOrders.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaSquad",
	'CodeFileName', "Code/PDAMilitiaSquad.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaSquads",
	'CodeFileName', "Code/PDAMilitiaSquads.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitiaStartPage",
	'CodeFileName', "Code/PDAMilitiaStartPage.lua",
}),
PlaceObj('ModItemCode', {
	'name', "PDAMilitaShopTrick",
	'CodeFileName', "Code/PDAMilitaShopTrick.lua",
}),
PlaceObj('ModItemMsgDef', {
	Description = "When a militia soldier gets promoted",
	Params = "unit, oldid",
	comment = "Fires after militia got promoted",
	id = "MilitiaPromoted",
}),
PlaceObj('ModItemOptionChoice', {
	'name', "huda_MilitiaCampaignCosts",
	'DisplayName', "Aditional costs when on campaign per 20hours of supply travel time",
	'DefaultValue', "40",
	'ChoiceList', {
		"0",
		"10",
		"20",
		"30",
		"40",
		"50",
		"60",
		"70",
		"80",
		"90",
		"100",
		"110",
		"120",
		"130",
		"140",
		"150",
		"160",
		"170",
		"180",
		"190",
		"200",
		"210",
		"220",
		"230",
		"240",
		"250",
		"260",
		"270",
		"280",
		"290",
		"300",
		"310",
		"320",
		"330",
		"340",
		"350",
		"360",
		"370",
		"380",
		"390",
		"400",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "huda_MilitiaEliteIncome",
	'DisplayName', "Daily Upkeep Elite",
	'DefaultValue', "100",
	'ChoiceList', {
		"0",
		"10",
		"20",
		"30",
		"40",
		"50",
		"60",
		"70",
		"80",
		"90",
		"100",
		"110",
		"120",
		"130",
		"140",
		"150",
		"160",
		"170",
		"180",
		"190",
		"200",
		"210",
		"220",
		"230",
		"240",
		"250",
		"260",
		"270",
		"280",
		"290",
		"300",
		"310",
		"320",
		"330",
		"340",
		"350",
		"360",
		"370",
		"380",
		"390",
		"400",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "huda_MilitiaRookieIncome",
	'DisplayName', "Daily Upkeep Rookie",
	'DefaultValue', "20",
	'ChoiceList', {
		"0",
		"10",
		"20",
		"30",
		"40",
		"50",
		"60",
		"70",
		"80",
		"90",
		"100",
		"110",
		"120",
		"130",
		"140",
		"150",
		"160",
		"170",
		"180",
		"190",
		"200",
		"210",
		"220",
		"230",
		"240",
		"250",
		"260",
		"270",
		"280",
		"290",
		"300",
		"310",
		"320",
		"330",
		"340",
		"350",
		"360",
		"370",
		"380",
		"390",
		"400",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "huda_MilitiaVeteranIncome",
	'DisplayName', "Daily Upkeep Veteran",
	'DefaultValue', "40",
	'ChoiceList', {
		"0",
		"10",
		"20",
		"30",
		"40",
		"50",
		"60",
		"70",
		"80",
		"90",
		"100",
		"110",
		"120",
		"130",
		"140",
		"150",
		"160",
		"170",
		"180",
		"190",
		"200",
		"210",
		"220",
		"230",
		"240",
		"250",
		"260",
		"270",
		"280",
		"290",
		"300",
		"310",
		"320",
		"330",
		"340",
		"350",
		"360",
		"370",
		"380",
		"390",
		"400",
	},
}),
PlaceObj('ModItemOptionToggle', {
	'name', "huda_militiaNoWeapons",
	'DisplayName', "Militia spawns without weapons",
	'DefaultValue', true,
}),
PlaceObj('ModItemTextStyle', {
	RolloverTextColor = 4291018156,
	TextColor = 4291018156,
	TextFont = T(448189319280, --[[ModItemTextStyle HUDASMALLPDASM TextFont]] "HMGothic Rough A, 10"),
	id = "HUDASMALLPDASM",
}),
PlaceObj('ModItemXTemplate', {
	id = "Test",
	PlaceObj('XTemplateWindow', nil, {
		PlaceObj('XTemplateWindow', nil, {
			PlaceObj('XTemplateWindow', {
				'__class', "XText",
			}),
			PlaceObj('XTemplateWindow', {
				'__class', "XText",
			}),
			}),
		PlaceObj('XTemplateWindow', nil, {
			PlaceObj('XTemplateWindow', nil, {
				PlaceObj('XTemplateForEach', nil, {
					PlaceObj('XTemplateWindow', nil, {
						PlaceObj('XTemplateWindow', {
							'__class', "XText",
						}),
						}),
					}),
				}),
			PlaceObj('XTemplateWindow', nil, {
				PlaceObj('XTemplateWindow', {
					'__class', "XText",
				}),
				}),
			}),
		}),
}),
PlaceObj('ModItemXTemplate', {
	id = "",
	PlaceObj('XTemplateConditionList', nil),
	PlaceObj('XTemplateGroup', nil),
}),
}
