return PlaceObj('ModDef', {
	'title', "Move Militia",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "hxmY4nT",
			'title', "Custom Settings",
			'version_major', 1,
			'version_minor', 3,
		}),
	},
	'id', "LXPER6t",
	'content_path', "Mod/LXPER6t/",
	'author', "permanent666",
	'version', 489,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"CharacterEffect/FarFromHome.lua",
		"CharacterEffect/GCMilitia.lua",
		"Code/Finances.lua",
		"Code/Init.lua",
		"Code/Movement.lua",
		"Code/Names.lua",
		"Code/SquadIcons.lua",
		"Code/Training.lua",
		"Code/Utils.lua",
	},
	'has_options', true,
	'saved', 1692408765,
	'code_hash', 4387279866450941110,
})